### ISSUE TITLE
How to handle the big tar size whose size exceeds the Integer.Max_value?

### ISSUE THREAD

**Issue by lawulu** [pgrandjean/TarballInputFormat#1]
There is a limit in the code: 
`        if (tarSize > Integer.MAX_VALUE) throw new IOException("tar entry " + tarEntry.getName() + " exceeds " + Integer.MAX_VALUE);
`

**Comment by pgrandjean** [comment]
The variable should be renamed `tarEntrySize`. It represents the size of a file/entry in a tarball. The input format reads the content into a `org.apache.hadoop.io.Text`, which wraps a Java array. Unfortunately, the max size of an array in Java is `Integer.MAX_VALUE`. As a consequence, this input format does not support entries with size greater than `Integer.MAX_VALUE`. Please note that the tarball itself can be of any size. The limitation is only on its entries.
In order to support entries larger than `Integer.MAX_VALUE`, `Text` has to be replaced by something else wrapping a collection that uses `Long` for size and indices.

**Comment by lawulu** [comment]
Got it. 
My task is to untar a big tar file, at first, I decided to write a mapreduce program using TarballInputFormat. Due to this issue, I have to write a Java program using the HDFS API to finish it.

Thanks for your quick response and explanation.
